### ISSUE TITLE
Warning: exec(): Unable to fork ["tesseract" --version 2>&1]

### ISSUE THREAD

**Issue by oyvindhauge** [nohn/watermeter#111]
**Describe the bug**
I have downloaded and started the Docker image following the instructions the the best of my ability. When I open the application for the first time, I get the error messages below. 

**To Reproduce**
Use the browser to open IP:3001

**Expected behavior**
Get the start page.

**Screenshots**
![image](https://github.com/nohn/watermeter/assets/288557/d4562c51-5555-4496-8f45-3dbb44a3dcaa)

**Additional context**
I am running Docker on a machine with Ubuntu. I have the latest version of Tesseract in the repo (version 4.1.1). The only change I did that I am aware of, is changing the external port from 3000 to 3001 because I have used 3000 for something else.

Any help is appreciated. Thanks!

```
Warning: exec(): Unable to fork ["tesseract" --version 2>&1] in /usr/src/watermeter/vendor/thiagoalessio/tesseract_ocr/src/Command.php on line 62

Warning: Undefined array key 0 in /usr/src/watermeter/vendor/thiagoalessio/tesseract_ocr/src/Command.php on line 63

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /usr/src/watermeter/vendor/thiagoalessio/tesseract_ocr/src/Command.php on line 63

Warning: Undefined array key 1 in /usr/src/watermeter/vendor/thiagoalessio/tesseract_ocr/src/Command.php on line 64

Warning: Trying to access array offset on value of type null in /usr/src/watermeter/vendor/thiagoalessio/tesseract_ocr/src/FriendlyErrors.php on line 87

Deprecated: version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated in /usr/src/watermeter/vendor/thiagoalessio/tesseract_ocr/src/FriendlyErrors.php on line 90

Warning: exec(): Unable to fork ["tesseract" --version 2>&1] in /usr/src/watermeter/vendor/thiagoalessio/tesseract_ocr/src/Command.php on line 62

Warning: Undefined array key 0 in /usr/src/watermeter/vendor/thiagoalessio/tesseract_ocr/src/Command.php on line 63

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /usr/src/watermeter/vendor/thiagoalessio/tesseract_ocr/src/Command.php on line 63

Warning: Undefined array key 1 in /usr/src/watermeter/vendor/thiagoalessio/tesseract_ocr/src/Command.php on line 64
```

**Comment by nohn** [comment]
@oyvindhauge please provide a screenshot of /configure.php

**Comment by oyvindhauge** [comment]
That was fast, here you go :)

![image](https://github.com/nohn/watermeter/assets/288557/cd4e8c08-2630-45e0-8ede-00ac04bb3dc1)

**Comment by nohn** [comment]
Hi @oyvindhauge. No I meant configure.php e.g. http://whatever:3001/configure.php

**Comment by oyvindhauge** [comment]
Sorry for not understanding and thank you for swift follow up. Here you go
![image](https://github.com/nohn/watermeter/assets/288557/63c7477f-a84f-445f-a9d1-205663cca691)

**Comment by nohn** [comment]
I am wondering a bit, what exactly you mean by "I have the latest version of Tesseract in the repo (version 4.1.1)". The docker container should ship with tesseract preinstalled. Please try executing this:

    docker exec -it watermeter tesseract --version

**Comment by oyvindhauge** [comment]
> The docker container should ship with tesseract preinstalled. Please try executing this:

Yes obviously it does, my bad. I just saw the error message and thought I did not have tesseract on my machine and installed it. That is not relevant, sorry.

The output is as follows:
```
tesseract 5.3.0
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 6b (libjpeg-turbo 2.1.2) : libpng 1.6.39 : libtiff 4.5.0 : zlib 1.2.13 : libwebp 1.2.4 : libopenjp2 2.5.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.6.2 zlib/1.2.13 liblzma/5.4.0 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.2
 Found libcurl/7.88.1 OpenSSL/3.0.9 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0 nghttp2/1.52.0 librtmp/2.3
```

**Comment by nohn** [comment]
What happens if you run the container manually?

    docker run -p 127.0.0.1:3001:3000 nohn/watermeter:latest

And then access http://127.0.0.1:3001/configure.php?

**Comment by oyvindhauge** [comment]
Same error message. Maybe the command line log output could give you a clue. Thanks again for following up on the problem.

![image](https://github.com/nohn/watermeter/assets/288557/88615e00-1399-4d51-8386-65fd79d2def0)
![image](https://github.com/nohn/watermeter/assets/288557/91df9867-968d-4c2b-ab12-ad681ba33368)

**Comment by nohn** [comment]
I still can't reproduce this. However, I did smaller changes that may affect this bug as well. Can you please pull the latest docker image and try again?

**Comment by oyvindhauge** [comment]
Hi and thanks for your help. It seems to be working now. The only think I have done is updating from Ubuntu 22.04 to 23.10. I have not manually done anything to the Docker image, but it is perhaps pulled automatically? Nevertheless, it seems to be working and I will explore the software further. Thanks again!

**Comment by vulcanjedi** [comment]
I have the same issues, so all the necessary components are not packaged in the container itself but requires my host machine?
