### ISSUE TITLE
Add support for decimal digits

### ISSUE THREAD

**Issue by nohn** [nohn/watermeter#16]

**Comment by nohn** [comment]
![example](https://user-images.githubusercontent.com/113465/109307657-44f44a80-7841-11eb-9b8f-72f524be4693.jpg)

**Comment by f00dagi** [comment]
This is the exact water meter that I have in my house (Sweden), support for that interface would be great!

**Comment by nohn** [comment]
Now available in develop Branch / Docker tag:

![image](https://user-images.githubusercontent.com/113465/156015451-b01b0f9c-981d-438b-875c-5611fb270ac3.png)

Will be merged to main Branch / Docker latest tag in the next few days no issues are risen in the beta tests.
