### ISSUE TITLE
Add support for ARM32/ARM64

### ISSUE THREAD

**Issue by mitchando96** [nohn/watermeter#28]
Hi I have been trying to get this working for a while on my Raspberry Pi 4 but keep getting this error.

standard_init_linux.go:228: exec user process caused: exec format error

Does watermeter support arm 32bit or 64 bit? I have tried both

**Comment by nohn** [comment]
Blocked by #9

**Comment by nohn** [comment]
Should work now. Your feedback is appreciated.
