### ISSUE TITLE
Create Howto

### ISSUE THREAD

**Issue by nohn** [nohn/watermeter#34]
See https://community.home-assistant.io/t/turning-analog-water-meters-into-a-home-assistant-sensor/282612/5

**Comment by f00dagi** [comment]
Thanks for the clarification, if you dont have time to support my requests simply tell me to stop.

A simple block diagram would be very useful to understand the setup.

1) Are you using Zero or Zero W?
2) Are you using the dedicated Raspberry Pi Zero camera?
3) What parts of your setup runs on the Zero?
3a) Raspberry Pi OS?
3b) Docker and Docker composer?
3c) The Python code?
4) Which containers parts are you referring to; Home assistant, watermeter, and?
5) Would it make sense to run everything on the Zero, apart from Home Assistant that is run on a separate physical machine?

Thanks!

**Comment by nohn** [comment]
> A simple block diagram would be very useful to understand the setup.

A generic overview looks like this, I'll elaborate on that later:

[ Camera ] => [ Watermeter ] == HTTP ==> [ Home Automation / Graphing ]

> 1. Are you using Zero or Zero W?
> 2. Are you using the dedicated Raspberry Pi Zero camera?
> 3. What parts of your setup runs on the Zero?
>    3a) Raspberry Pi OS?
>    3b) Docker and Docker composer?
>    3c) The Python code?

You obviously need a photo of your water meter.

To achieve that, the Pi is not the key. It's just what I use. I didn't have a regular USB webcam at hand but a Pi Zero W and some cheap raspi-camera (one that connects via flat cable). So what runs on my Pi? Raspberry Pi OS. Via cron, an image is taken every minute (using the python script) and post-processed using imagemagick to improve the results. I use imagemagick -contrast -equalize, but it strongly depends on the setup - what is the light situation, how good is the camera, what's the distance between camera and watermeter etc. I serve the image through HTTP using NGINX, but again: That's my setup. It doesn't need to be yours. If your run everything on one machine, you could serve the image via local filesystem as well.

So far in overview it looks like this:

[ Camera ] == HTTP ==> [ Watermeter ] == HTTP ==> [ ... ]

With [ Camera ] looking like this:

[ Cron ] -> [ Turn on LED ] => [ Shoot Image ] => [ Turn off LED ] => [ Post-Process image ] => [ Serve image via NGINX ]

> 4. Which containers parts are you referring to; Home assistant, watermeter, and?

The only container I'm referring to is watermeter. 

The whole picture is:

[ Camera ] == HTTP ==> [ Watermeter ] == HTTP ==> [ Home Assistant ] == HTTP ==> [ InfluxDB ] == HTTP ==> [ Grafana ]

> 5. Would it make sense to run everything on the Zero, apart from Home Assistant that is run on a separate physical machine?

I've never tried that, but I guess it would work. RAM usage is negligible, CPU usage is significant but should still be low enough for running on a Zero.

**Comment by f00dagi** [comment]
Thanks for the answers, I will proceed accordingly and place a purchase order for the items.

Can this issue be re-opened to enable me to ask some more questions on how to get started?

For troubleshooting purposes I have now installed Docker and Docker compose on a Windows machine, I created a new "Dev Environment" and used your repository as input: https://github.com/nohn/watermeter. Within the Docker container I then created "docker-composer.yml" and ran "docker-composer up" without any issues.

What's next, I dont understand how (and where) to use the PHP code
`git pull https://github.com/nohn/watermeter.git
composer install
cd src/
php -S 127.0.0.1:3000`

Please advice. Thanks!

**Comment by nohn** [comment]
I've added an extensive Howto at https://github.com/nohn/watermeter/blob/main/doc/HOWTO.md. That should cover everything from start to end.

However from your last comment I discern that you are new to Docker and Docker Compose. I don't know anything about Docker on Windows and creating a Dev Environment using a Git repository as source sounds strange to me. Please try to follow the howto step by step and open new tickets for everything you stumble upon. I would recommend to run everything on Linux (even a Linux VM in Windows makes more sense to me than Docker on Windows).

If you are also new to Raspi Hardware (like soldering an LED to the GPIOs etc.) and Home Assistant, you are entering a path of trial and tribulation but one that's worth the hassle.

**Comment by f00dagi** [comment]
Thanks alot, I will follow your guide, it looks very detailed.

Yes, I am a total newbie to Docker and Docker compose. I believe I had some progress last night but will leave that for now and try directly on RPi instead according to you guide.

The RPi hardware is more known to me than the Docker, Linux parts but regardless I like to learn new things and can be quite stubborn.

Thanks again for your time.

**Comment by nohn** [comment]
OK. Have fun!

**Comment by f00dagi** [comment]
I do not yet have the camera but it should be possible to test the setup anyway by manually feeding it with an image? I am running the below on a Raspberry Pi 4.

Following your guide I have 
- installed ngix and applied the changes you suggest
- installed imagemagick and tested it with -crop
- installed docker-compose, enabled at startup and added the pi user
- created the docker-compose.yaml (in the root) and run docker-compose pull && docker-compose up -d

Uncertainties
- I ran mkdir -p watermeter/config in the root, is that correct, the folder is empty
- How can I confirm that watermeter is actually running?
- Where in my installation should I be able to find the configure.php, index.php, config.php that are present in you git repository?

In the browser at http://192.168.1.111:3000/configure.php I get the following errors:
Warning: require(config/config.php): Failed to open stream: No such file or directory in /usr/src/watermeter/src/configure.php on line 3

Fatal error: Uncaught Error: Failed opening required 'config/config.php' (include_path='.:/usr/local/lib/php') in /usr/src/watermeter/src/configure.php:3 Stack trace: #0 {main} thrown in /usr/src/watermeter/src/configure.php on line 3

Thanks!

**Comment by nohn** [comment]
No mistake on your side. In fact you found a bug in the HOWTO. I fixed that. The key part is

```curl https://raw.githubusercontent.com/nohn/watermeter/main/src/config/config.php -o watermeter/config/config.php```

After running that command from shell, please reload http://192.168.1.111:3000/configure.php and you should be done.

**Comment by f00dagi** [comment]
No luck.

Running `curl https://raw.githubusercontent.com/nohn/watermeter/main/src/config/config.php -o watermeter/config/config.php` gives me the error "Warning: Failed to create the file watermeter/config: file or folder does not exist".

I would guess the curl command should copy the config.php from github to my folder, I did that manually and get this error in the browser: 

Warning: file_get_contents(config/lastValue.txt): Failed to open stream: No such file or directory in /usr/src/watermeter/src/index.php on line 5

Warning: filemtime(): stat failed for config/lastValue.txt in /usr/src/watermeter/src/index.php on line 6

Fatal error: Uncaught TypeError: Unsupported operand types: string - string in /usr/src/watermeter/src/index.php:144 Stack trace: #0 {main} thrown in /usr/src/watermeter/src/index.php on line 144

Looks like more files are missing?

**Comment by f00dagi** [comment]
Thanks, I see watermeter in the browser now!

**Comment by nohn** [comment]
Did you do anything to make it work, or did it just magically start to work?

**Comment by f00dagi** [comment]
Well, I guess it was newbie mistakes, I did not have the right (sudo) permission to write the file but it also seems that `sudo docker-compose pull && docker-compose up -d` must be run in the file system root. Could that be the case? I tried to replicate on a second pi and came to the same conclusion.

Next question, I really cannot figure it out, how do I get the detected OCR to home assistant, using your image?
At http://192.168.1.245:3000/?debug it says value: 819.7797 which obviously is correct.
At http://192.168.1.245:3000/ is simply says 0, I would have expected to find 819.7797 there as well?
The sensor is added to configuration.yaml and I can find sensor.water after a reboot but it instead of showing 819.7797 it gives a string:

<br /> <b>Fatal error</b>: Uncaught TypeError: Cannot access offset of type string on string in /usr/src/watermeter/src/index.php:30 Stack trace: #0 {main} thrown in <b>/usr/src/watermeter/src/index.php</b> on line <b>30</b><br /> 

I am still using your image and have not yet hooked up a camera and do not yet run the watermeter-py and the convert -crop, -contrast, but that should not matter?

**Comment by f00dagi** [comment]
I have now been through all parts including adding a logitech webcam, setting up a cron, cropping and turning on a LED.

The only part I cant get right is as described above and with the image below to get the OCR identified number into the lastValue.txt and Home Assistant. Any ideas would be most appreciated, this is the only piece I am missing before I can try it for real.

Thanks!

![Skärmklipp](https://user-images.githubusercontent.com/56124786/133907564-1ab57a32-9544-4bc1-9ab7-47be8e934ed6.PNG)

**Comment by nohn** [comment]
Can you please provide the raw image from your camera?

**Comment by f00dagi** [comment]
This is an unprocessed image from my camera. Obviously not a watermeter but for testing purposes it would suffice?

Thanks!

![2021-09-18_2150](https://user-images.githubusercontent.com/56124786/133921244-1ffbd3a3-b647-4258-a2f2-744902aa9251.jpg)

**Comment by nohn** [comment]
You need to preprocess the image, so the digits have a higher contrast:

1. Crop off anything that's not required
2. Play around a bit with contrast, white balance etc.

Result should look something like thos:

![enhance](https://user-images.githubusercontent.com/113465/133936402-afbd95d4-630d-4fed-acb5-c8349177e454.jpg)

With that, recognition works:

![Screenshot from 2021-09-19 19-08-25](https://user-images.githubusercontent.com/113465/133936429-cc54aa46-7549-48de-bfeb-b1d4a45d2cc1.png)

![Screenshot from 2021-09-19 19-08-29](https://user-images.githubusercontent.com/113465/133936433-2fbdd464-1933-4e7c-ad21-98c68a796666.png)

**Comment by nohn** [comment]
I looked more into what's happening on your side:

1. When doing the initial configuration you need to set the "Initial Value" to whatever is your current value. Any increase that's higher than the threshold will be ignored (https://github.com/nohn/watermeter/blob/main/src/index.php#L144)
2. (so if you only work with digits and no gauges, unless #16 is resolved, you'd have to set the threshold to at least 1.)

**Comment by f00dagi** [comment]
Thanks, setting the initial value and the threshold made all the difference, the correct number is now detected through OCR and feed to Home Assistant as expected. I will proceed to start taking pictures of the actual water meter and see if I can get it up and running.

If you want more unexpected behaviours (maybe I should file a separate bug report?) to look at I often get the error message as per image three when I press the buttons "Add a digit" or "Add a guage" in the configuration interface.

Thanks alot for your efforts!

![1](https://user-images.githubusercontent.com/56124786/133940845-49982c8e-d26b-4539-9eeb-ab4dcc2950e9.PNG)
![2](https://user-images.githubusercontent.com/56124786/133940848-e6d77965-57df-4dbc-8c4c-642280c43080.PNG)
![3](https://user-images.githubusercontent.com/56124786/133940851-3181c1ed-dc5f-442f-a429-25a5b674569e.PNG)

**Comment by f00dagi** [comment]
Shifting to my watermeter, using the same photo over and over without getting any reliable OCR reading. I have tried tweaking white balance, contrast, brightness in GIMP before running it through watermeter but no real correlation between settings and results. I manage to get an OCR reading of the '4', the '9' and also '49' but no success in '493'.

To me the OCR engine seems to be extremely sensitive and I cannot see how it would work when the numbers will move around even slightly between images of an actual watermeter. Probably am I doing something wrong. All other parts of the setup (webcam, diode, crontab, ...) are working as expected and are ready to go but to me the OCR behaviour became a stopper today.

I provided my original imaget at the bottom.

-Daniel

![1](https://user-images.githubusercontent.com/56124786/134062212-44503613-8026-47c8-a61f-a5c4f2ddb34c.PNG)
![2](https://user-images.githubusercontent.com/56124786/134062219-d881cec8-2acc-40e7-acb8-08e29fa5b9e8.PNG)
![watermeter_f00dagi_original](https://user-images.githubusercontent.com/56124786/134062228-67814c93-2ff6-4465-8c24-eb476a803229.jpg)

**Comment by nohn** [comment]
Your image is too good ;)

So I did two things:

1. run your image through imagemagick and tune brightness and contrast to extreme values:```convert in.jpg -brightness-contrast 40x50 out.jpg && eog out.jpg ```. The result is 
![demo3](https://user-images.githubusercontent.com/113465/134072851-ca5a0bf9-1920-48cd-981b-ac37c67af0f4.jpg)
2. added on option to disable Digit Postprocessing

You need both. To fetch the new version run ```docker-compose pull && docker-compose up -d``` in whatever directory your docker-compose.yaml is.

The results look fine to me:

![Screenshot from 2021-09-20 22-45-50](https://user-images.githubusercontent.com/113465/134073306-3b9d0f8f-26dd-495e-b748-d7135e988912.png)

![Screenshot from 2021-09-20 22-45-44](https://user-images.githubusercontent.com/113465/134073273-e4f67c89-33ec-458f-b6b4-bfbe47c033a2.png)
