### ISSUE TITLE
'Add a digit' results in error

### ISSUE THREAD

**Issue by f00dagi** [nohn/watermeter#36]
Hi!

In the configure user interface, when I press 'Add a Digit' or 'Add a Gauge', I get the error message:
`Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /usr/src/watermeter/src/configure.php:111 Stack trace: #0 {main} thrown in /usr/src/watermeter/src/configure.php on line 111`

See attached images.

Pressing 'back' in the browser and then 'preview', 'save' takes me out of the error state but I cannot add Digits och Gauges which is rather limiting.

A workaround for me is to update config.php manually with more Digits.

![bild](https://user-images.githubusercontent.com/56124786/134150835-67a52322-e009-4122-99fd-5a713b2d7ba5.png)
![bild](https://user-images.githubusercontent.com/56124786/134150897-106abfe6-a6e4-4c96-8663-f3814ef2546b.png)

**Comment by nohn** [comment]
Fixed. Please pull the lastest docker image.
