### ISSUE TITLE
Feature request: validate detected digits

### ISSUE THREAD

**Issue by f00dagi** [nohn/watermeter#38]
Since the rightmost digital value consists of a rotating cylinder it's value is not always centered in the OCR detection rectangle.

It would be great if watermeter could identify that the number of OCR rectangles does not correspond to the number of OCR detected digits and in that case not update the Home Assistant sensor.

Basically, if the detection of one digit is unsuccessful, the number is not reported to the sensor.

![bild](https://user-images.githubusercontent.com/56124786/134569775-2c404149-e766-4386-9790-f79e8833d7c0.png)

**Comment by nohn** [comment]
Out of curiosity: What's the threshold, you've configured?

**Comment by nohn** [comment]
With the support for post decimal digits (#16), this should be solved given you set a sane threshold (something less than or equal to 0.001 in case of your meter)
