### ISSUE TITLE
Analog Only Gas Meter

### ISSUE THREAD

**Issue by tommyjlong** [nohn/watermeter#43]
I have a gas meter that has 4 analog gauges on it (no digital digits).  I am trying out the `nohn/watermeter` to see if I can get it to work for my gasmeter.  My first attempt didn't work so well, so looking for some help.

Since the watermeter expects at least one digital digit, I found a "0" that is _printed_ on the gasmeter itself that I used to mimic a digital digit. Otherwise I have setup 4 analog gauges.  The actual meter I am testing is not the real one, it is a used one I purchased separately so that I could play with it as part of my test setup (for example, I can turn a knob in the back of the meter to change the gauge dials).  It came with all the analog gauges set to 0 and that's what I started my testing with.  I set the `initial value` to 0. Attached is a partial snapshot of the debug output, and none of the gauges were interpreted correctly (however the "0" digital digit seems be recognized properly).
![MeterDebug](https://user-images.githubusercontent.com/35182132/138532340-cb5dd2cc-6544-434e-a5f0-668633b7d608.jpg)
```
hasErrors: 1
array(7) {
  [76]=>
  string(46) "Could not interpret . Using last known value 0"
  [149]=>
  bool(true)
  [150]=>
  bool(true)
  [151]=>
  array(1) {
    [0]=>
    bool(true)
  }
  [152]=>
  array(1) {
    [0]=>
    string(6) "0.5839"
  }
  [153]=>
  array(1) {
    [0]=>
    string(4) "0000"
  }
  [154]=>
  array(1) {
    [0]=>
    float(0.5839)
  }
}
lastValue: 0000
value: 0.5839
0000
```
There are some other quirks with this meter, as some of the gauges are the usual 0 to 9 clockwise, but others are 9 to 0 clockwise.
Looking for some ideas, but for starters, looking for advice on how to get the 0 to 9 clockwise gauges to be recognized properly.  BTW, thanks for your work on this :)

**Comment by nohn** [comment]
Sorry. This meter is so strange in so many aspects, I won't support that extreme edge case.
