### ISSUE TITLE
Value from water-meter to Home Assistant

### ISSUE THREAD

**Issue by DastyDiesel** [nohn/watermeter#51]
**Introduction of my topic** - I installed water-metter to ESP-CAM (works OK). I checked MQTT setting and filled full IP address of broker (mqtt://192.....:1883). I opened Home Assistant (runs on Raspberry Pi 4, Zigbee USB module) and I tried to add integration of MQTT - but when I added IP address of broker of water-meter, the Home Assistant didn't find it. 

**Question:** what have I to do for transfer of value from water-mteer to Home Assistant using MQTT? I'm little bit lost n MQTT area.

Thank you

**Comment by nohn** [comment]
Looks like you are looking for help regarding https://github.com/jomjol/AI-on-the-edge-device.
