### ISSUE TITLE
Fatal error: Uncaught DivisionByZeroError

### ISSUE THREAD

**Issue by onkelfarmor** [nohn/watermeter#65]
Get this error ...

Raw OCR: 
Clean OCR: Digital Preview
Choosing last value 0
Digital: 0

Fatal error: Uncaught DivisionByZeroError: Division by zero in /usr/src/watermeter/vendor/nohn/analogmeterreader/src/AnalogMeter.php:173 Stack trace: #0 /usr/src/watermeter/vendor/nohn/analogmeterreader/src/AnalogMeter.php(69): nohn\AnalogMeterReader\AnalogMeter->processImage(false) #1 /usr/src/watermeter/classes/Reader.php(131): nohn\AnalogMeterReader\AnalogMeter->getValue() #2 /usr/src/watermeter/classes/Reader.php(46): nohn\Watermeter\Reader->readGauges() #3 /usr/src/watermeter/public/configure.php(202): nohn\Watermeter\Reader->getReadout() #4 {main} thrown in /usr/src/watermeter/vendor/nohn/analogmeterreader/src/AnalogMeter.php on line 173

**Comment by nohn** [comment]
Could you please share your configuration and an image for your meter as you feed it into watemeter?

**Comment by nohn** [comment]
Please try with the lastest version. If it still occurs, please reopen this ticket providing your configuration and image.
