### ISSUE TITLE
Add possibility to execute command before and after fetching image

### ISSUE THREAD

**Issue by Strixx76** [nohn/watermeter#68]
I am about to test this project next week, by using a ESP-CAM and ESPHome. But I am at the moment struggling with a nice way to turn the camera light on and off. ESPHome doesn't seem to have support for automation on accessing the camera.

So one way to solve this would be if I could curl before and after the picture is taken.

**Comment by nohn** [comment]
I don‘t see this a feature in watermeter. It relies on an image already taken. You could however easily automate that in Home Assistant.
