### ISSUE TITLE
Image cropping not taking into account start X/Y 

### ISSUE THREAD

**Issue by hansbruy** [nohn/watermeter#92]
Hi Sebastian,

with the version I loaded 26th and 27th Dec the cropping starting positions for X and Y are not taken into account (tested on Opera-browser). In the example below positions should start at (515,280) but seems they remain at (0,0).

Sample of input, output and config.php enclosed

![image](https://user-images.githubusercontent.com/78865207/209665253-fdd6e7df-7993-4cbb-9c86-9656f36c8868.png)
[config.php.txt](https://github.com/nohn/watermeter/files/10308054/config.php.txt)
![meters_20221227-130000](https://user-images.githubusercontent.com/78865207/209665311-dabb26cb-0e6f-43ab-9d73-0e5c84cb5c35.jpg)

Thanks,
Hans

**Comment by nohn** [comment]
StartX + Width are not allowed to be larger than the width of the original image. Same for StartY + Height. If you set both to be <= the dimensions the image, everything works fine:

![image](https://user-images.githubusercontent.com/113465/209698520-839807ac-3a78-4715-9b7d-103a6ed53c29.png)

**Comment by hansbruy** [comment]
Indeed - update accordingly and now OK
